debug: true
domain: main.domain
response: json
allowHeaders:
  - X-JWT

#-------------------------------------------
routes:
  /:
    GET: Dewep\Demo::demo

#-------------------------------------------
middleware:
  before:
    Dewep\Middleware\CookieUserAuth\CookieUserAuth: &CookieUserAuth
      name: id
      secret: 'secret key'
      exp: 3600
      domain: main.domain

  after:
    Dewep\Middleware\CookieUserAuth\CookieUserAuth: *CookieUserAuth
    Dewep\Middleware\Debug:
      name: app.log


#-------------------------------------------
providers:
  logger:
    _: Dewep\Providers\LoggerProvider
    debug: true
    name: app
    filename: app.log

  mysql:
    _: Dewep\Providers\MysqlProvider
    host: localhost
    port: 3306
    dbname: default
    login: default
    password: default

  twig:
    _: Dewep\Providers\TwigProvider

  redis:
    _: Dewep\Providers\RedisProvider
    scheme: 'tcp'
    host: 'redis'
    port: 6379

#-------------------------------------------


