debug: true

response: json

routes:
  /:
    GET: Dewep\Demo::demo

middleware:
  request:
    Dewep\Middleware\Auth:
      cookie: x-token

  response:
    Dewep\Middleware\Debug:
      name: app.log


providers:
  logger:
    _: Dewep\Providers\LoggerProvider
    debug: true
    name: app
    filename: app.log

  mysql:
    _: Dewep\Providers\MysqlProvider
    host: localhost
    port: 3306
    dbname: default
    login: default
    password: default

    