debug: true
domain: main.domain
response: json
allowHeaders:
  - X-JWT

#-------------------------------------------
routes:
  /public/page/{id:\d+}:
    GET: Dewep\Demo::demo
  /private/page/{name}:
    _: Dewep\Middleware\Guard
    GET: Dewep\Demo::demo

#-------------------------------------------
middleware:
  before:
    cookie: &CookieUserAuth
      _: Dewep\Middleware\Auth\Cookies
      name: id
      secret: 'secret key'
      exp: 3600
      domain: localhost

  after:
    cookie: *CookieUserAuth
    debug:
      _: Dewep\Middleware\Debug
      name: app.log


#-------------------------------------------
providers:
  logger:
    _: Dewep\Providers\LoggerProvider
    debug: true
    name: app
    filename: app.log

  mysql:
    _: Dewep\Providers\MysqlProvider
    host: localhost
    port: 3306
    dbname: default
    login: default
    password: default

  twig:
    _: Dewep\Providers\TwigProvider

  redis:
    _: Dewep\Providers\RedisProvider
    scheme: 'tcp'
    host: 'redis'
    port: 6379

#-------------------------------------------
console:
  app.restore: Dewep\Handlers\Consoles\CreateDirs

