debug: true

response: json

routes:
  /:
    GET: Dewep\Demo::demo

middleware:
  request:
    - Dewep\Middleware\Auth
  response:
    - Dewep\Middleware\Debug


providers:
  logger: Dewep\Providers\LoggerProvider
  mysql: Dewep\Providers\MysqlProvider



mysql:
  host: localhost
  port: 3306
  dbname: default
  login: default
  password: default
    