<?php

namespace Dewep;

use Dewep\Handlers\BlankApp;
use Dewep\Interfaces\ApplicationInterface;

class Console extends BlankApp implements ApplicationInterface
{
    public function __construct()
    {
        parent::__construct();
    }

    public function bootstrap()
    {
        parent::bootstrap(); // TODO: Change the autogenerated stub
    }


}
